title: CS110 Winter '20
email: vanwars@northwestern.edu
description: >- # this means to ignore newlines until "baseurl:"
  Intro to Computer Programming with Python
baseurl: "/winter2020" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  vanwars

# Build settings
markdown: kramdown
theme: "just-the-docs"
remote_theme: "eecs110/just-the-docs"

# search_enabled: true

aux_links:
    "Piazza <i class='fas fa-external-link-alt'></i>":
      - "//piazza.com/northwestern/winter2020/cs110/home"
